### ISSUE TITLE
The /polls/<poll-id>/results/raw endpoint

### ISSUE THREAD

**Issue by roipoussiere** [MieuxVoter/mv-api-spec#12]
There is one thing that I find very interesting (among others) in majority judgment: **data**.

Or more exactly, the ability to deeply study the raw results of a mj election. Raw results are not the final merit profile or table as we are used to see, but the number of participants that voted for what.

A MJ ballot can be represented like this:

|  | reject | insufficient | poor | fair | good | very good | excellent |
|---|---|---|---|---|---|---|---|
| proposal 1 | ◻ | ◼ | ◻ | ◻ | ◻ | ◻ | ◻ |
| proposal 2 | ◻ | ◻ | ◻ | ◻ | ◼ | ◻ | ◻ |
| proposal 3 | ◻ | ◻ | ◻ | ◻ | ◻ | ◻ | ◼ |
| proposal 4 | ◻ | ◻ | ◻ | ◻ | ◼ | ◻ | ◻ |

The data I want, is how many people voted this specific ballot. And how many people voted for a specific other one, etc.

This will allow many data analysis, such as: *If I remove this proposal, what could be the election result?*, or *Among the people that voted Excellent for this proposal, how they voted for all other proposals?*, etc.

So a ballot result can be identified by listing the result of each proposal, sequentially. In the example above; it's: insufficient, good, excellent, good. If we give a 1-char reference for each mention, such as `a`: reject, `b`: insufficient: etc. then this ballot can be identified by this simple id: `bege`.

Now the full dataset can be represented by a dictionary of [ballot result id / number of participants that voted this ballot result]. Here is an example of a dataset file that also includes some poll metadata: 

```yaml
_question: 'Blablablah?'
_proposals: ['foo', 'bar', 'baz', 'bat']
_mentions: ['reject', 'insufficient', 'poor', 'fair', 'good', 'very good', 'excellent']
_nb_participants: 144
bege: 15
abea: 8
eecg: 12
fccb: 5
# etc.
```

The `/polls/<poll-id>/results/raw` endpoint could return a such file. Other information could be 

Just to give an order of magnitude of the response size: encoded in yaml, for a poll with 10 proposals, each line will have a length of ~15 characters. If there are 1000 participants that vote for 1000 different ballots, the response fits in 15 kbytes.
